global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "toxicity-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend-api:8000"]
        labels:
          service: "toxicity-classifier"
